DROP TABLE SYS_USER_ROLE_REL;

DROP TABLE SYS_USER;

DROP TABLE SYS_ORG;

DROP TABLE SYS_ROLE_RES_REL;

DROP TABLE SYS_RES;

DROP TABLE SYS_ROLE;

CREATE TABLE SYS_ORG
(
	ORG_ID               VARCHAR(32) NOT NULL,
	ORG_NAME             VARCHAR(100) NULL,
	UP_NO                VARCHAR(32) NOT NULL,
	ORG_NO               VARCHAR(32) NOT NULL,
	AVL                  boolean NULL,
	UP_NO_PATH           VARCHAR(1000) NULL
);

ALTER TABLE SYS_ORG
ADD PRIMARY KEY (ORG_ID);

CREATE TABLE SYS_RES
(
	RES_ID               VARCHAR(32) NOT NULL,
	RES_NAME             VARCHAR(100) NULL,
	RES_TYPE             VARCHAR(10) NULL,
	AVL                  boolean NULL,
	RES_NO               VARCHAR(32) NOT NULL,
	UP_NO                VARCHAR(32) NOT NULL,
	UP_NO_PATH           VARCHAR(32) NOT NULL,
	PRMT_DEF             VARCHAR(100) NULL,
	CRE_TIME             DATETIME NULL
);

ALTER TABLE SYS_RES
ADD PRIMARY KEY (RES_ID);

CREATE TABLE SYS_ROLE
(
	ROLE_ID              VARCHAR(32) NOT NULL,
	ROLE_NAME            VARCHAR(100) NULL,
	REMARK               VARCHAR(500) NULL,
	AVL                  boolean NULL,
	ROLE_NO              VARCHAR(32) NOT NULL
);

ALTER TABLE SYS_ROLE
ADD PRIMARY KEY (ROLE_ID);

CREATE TABLE SYS_ROLE_RES_REL
(
	ROLE_ID              VARCHAR(32) NOT NULL,
	RES_ID               VARCHAR(32) NOT NULL
);

ALTER TABLE SYS_ROLE_RES_REL
ADD PRIMARY KEY (ROLE_ID,RES_ID);

CREATE TABLE SYS_USER
(
	USER_ID              VARCHAR(32) NOT NULL,
	USERNAME             VARCHAR(100) NULL,
	PASSWORD             VARCHAR(24) NULL,
	ORG_ID               VARCHAR(32) NULL,
	AVL                  boolean NULL,
	CRE_DATE             DATETIME NULL,
	LAST_UPDT_DATE       DATETIME NULL
);

ALTER TABLE SYS_USER
ADD PRIMARY KEY (USER_ID);

CREATE TABLE SYS_USER_ROLE_REL
(
	USER_ID              VARCHAR(32) NOT NULL,
	ROLE_ID              VARCHAR(32) NOT NULL
);

ALTER TABLE SYS_USER_ROLE_REL
ADD PRIMARY KEY (USER_ID,ROLE_ID);
